---
settings:
  name: Amazon FSx for NetApp ONTAP
  platform: cloud
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Amazon FSX für NetApp ONTAP Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    url: "/whats-new.html"
  - title: Los geht's
    entries:
    - title: Weitere Informationen zu Amazon FSX für NetApp ONTAP
      url: "/start/concept-fsx-aws.html"
    - title: Schnellstart
      url: "/start/task-getting-started-fsx.html"
    - title: Berechtigungen einrichten
      url: "/requirements/task-setting-up-permissions-fsx.html"
    - title: Erstellen oder ermitteln Sie eine Arbeitsumgebung
      url: "/use/task-creating-fsx-working-environment.html"
  - title: Verwaltung eines FSX für ONTAP-Dateisystems
    url: "/use/task-manage-working-environment.html"
  - title: Überwachen Sie den Betrieb mit Tracker
    url: "/use/task-monitor-operations.html"
  - title: Entfernen eines Dateisystems aus einem Arbeitsbereich
    url: "/use/task-remove-filesystem.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/support/task-support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/support/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
