---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, cloud manager' 
summary: Erfahren Sie mehr über die Neuerungen in Amazon FSX for NetApp ONTAP. 
---
= Neuerungen bei Amazon FSX for NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Erfahren Sie mehr über die Neuerungen in FSX for ONTAP.



== 30 Juli 2023



=== Unterstützung für drei weitere Regionen

Kunden können jetzt Amazon FSX for NetApp ONTAP-Dateisysteme in drei neuen AWS-Regionen erstellen: Europa (Zürich), Europa (Spanien) und Asien-Pazifik (Hyderabad).

Siehe link:https://aws.amazon.com/about-aws/whats-new/2023/04/amazon-fsx-netapp-ontap-three-regions/#:~:text=Customers%20can%20now%20create%20Amazon,file%20systems%20in%20the%20cloud["Amazon FSX for NetApp ONTAP ist jetzt in drei weiteren Regionen verfügbar"^] Vollständige Informationen.



== 02 Juli 2023



=== Fügen Sie eine Storage-VM hinzu

Das ist jetzt möglich link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-add-fsx-svm.html["Fügen Sie eine Storage-VM hinzu"] Zu dem Filesystem Amazon FSX für NetApp ONTAP mit BlueXP.



=== **Meine Möglichkeiten** Tab ist jetzt **Mein Anwesen**

Die Registerkarte **Meine Möglichkeiten** ist jetzt **Mein Anwesen**. Die Dokumentation wird aktualisiert, um den neuen Namen wiederzugeben.



== 04 Juni 2023



=== Startzeit des Wartungsfenster

Wenn link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html#create-an-amazon-fsx-for-netapp-ontap-working-environment["Schaffung einer Arbeitsumgebung"], Sie können die Startzeit für das wöchentliche 30-minütige Wartungsfenster angeben, um sicherzustellen, dass die Wartung nicht mit kritischen Geschäftsaktivitäten in Konflikt steht.



=== Verteilung von Volume-Daten über FlexGroups

Wenn link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-add-fsx-volumes.html["Erstellen eines Volumes"], Sie können die Datenoptimierung durch Erstellen einer FlexGroup zur Verteilung von Daten über Volumes.



== 07 Mai 2023



=== Erstellen Sie eine Sicherheitsgruppe

Wenn Sie eine Arbeitsumgebung erstellen, können Sie jetzt über BlueXP  verfügenlink:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-creating-fsx-working-environment.html#create-an-amazon-fsx-for-netapp-ontap-working-environment["Erstellen Sie eine Sicherheitsgruppe"], die nur den Datenverkehr innerhalb der ausgewählten VPC zulässt. Diese Funktion link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/requirements/task-setting-up-permissions-fsx.html["Erfordert zusätzliche Berechtigungen"].



=== Tags hinzufügen oder ändern

Sie können optional link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-add-fsx-volumes.html#create-volumes["Zusatz"]Volumes und link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-manage-fsx-volumes.html#manage-volume-tags["Ändern"] Tags zum Kategorisieren von Volumes erstellen.



== Bis 02. April 2023



=== Erhöhung der IOPS-Grenze

Die IOPS-Grenze wird erhöht und ermöglicht eine manuelle oder automatische Provisionierung von bis zu 160,000.



== 05 März 2023



=== Verbesserte Benutzeroberfläche

Die Benutzeroberfläche wurde verbessert und Screenshots wurden in der Dokumentation aktualisiert.



== 01 Januar 2023



=== Automatisches Kapazitätsmanagement

Sie können jetzt aktivierenlink:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-manage-working-environment.html#manage-automatic-capacity["Automatisches Kapazitätsmanagement"], um je nach Bedarf inkrementellen Storage hinzuzufügen. Das automatische Kapazitätsmanagement fragt das Cluster in regelmäßigen Abständen ab, um den Bedarf zu ermitteln. Es erhöht die Storage-Kapazität automatisch in Schritten von 10 % bis zu 80 % der maximalen Kapazität des Clusters.



== 18. September 2022



=== Ändern Sie Storage-Kapazität und IOPS

Sie können jetzt link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-manage-working-environment.html#change-storage-capacity-and-IOPS["Ändern Sie Storage-Kapazität und IOPS"]jederzeit, nachdem Sie die FSX für ONTAP Arbeitsumgebung erstellt haben.



== 31 Juli 2022



=== *Mein Anwesen* Feature

Wenn Sie Ihre AWS-Anmeldeinformationen bereits bei Cloud Manager angegeben haben, kann die neue Funktion *Mein Bestand* automatisch FSX für ONTAP-Dateisysteme erkennen und vorschlagen, die mit Cloud Manager hinzugefügt und verwaltet werden sollen. Sie können die verfügbaren Datendienste auch über die Registerkarte *My estate* überprüfen.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-creating-fsx-working-environment.html#discover-an-existing-fsx-for-ontap-file-system["Entdecken Sie FSX for ONTAP mit My Estate"]



=== Durchsatzkapazität ändern

Sie können jetzt link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-manage-working-environment.html#change-throughput-capacity["Durchsatzkapazität ändern"]jederzeit, nachdem Sie die FSX für ONTAP Arbeitsumgebung erstellt haben.



=== Datenreplizierung und -Synchronisierung

Sie können jetzt link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-manage-fsx-volumes.html#replicate-and-sync-data["Datenreplizierung und -Synchronisierung"] zu On-Premises- und anderen FSX für ONTAP-Systemen mit FSX für ONTAP als Quelle zugreifen.



=== Erstellen Sie ein iSCSI-Volume

Sie können jetzt link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-add-fsx-volumes.html#creating-volumes["Erstellen Sie iSCSI Volumes in FSX für ONTAP mit Cloud Manager"].



== 3 Juli 2022



=== Unterstützung für Single oder Multiple Availability Zon

Sie können sich nun für ein HA-Implementierungsmodell mit einer einzelnen oder mehreren Verfügbarkeitszonen entscheiden.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-creating-fsx-working-environment.html#create-an-amazon-fsx-for-ontap-working-environment["FSX für ONTAP-Arbeitsumgebungen erstellen"]



=== Unterstützung von GovCloud Kontenauthentifizierung

In Cloud Manager wird nun die AWS GovCloud Kontoauthentifizierung unterstützt.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/requirements/task-setting-up-permissions-fsx.html#set-up-the-iam-role["Einrichten der IAM-Rolle"]



== 27 Februar 2022



=== Übernehmen Sie die IAM-Rolle

Wenn Sie eine FSX für die Arbeitsumgebung von ONTAP erstellen, müssen Sie nun das ARN einer IAM-Rolle bereitstellen, von der Cloud Manager ausgehen kann, eine FSX für ONTAP Arbeitsumgebung zu erstellen. Zuvor mussten Sie AWS Zugriffsschlüssel bereitstellen.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/requirements/task-setting-up-permissions-fsx.html["Erfahren Sie, wie Sie Berechtigungen für FSX für ONTAP einrichten"].



== Oktober 31 2021



=== Erstellen Sie iSCSI-Volumes mit der Cloud Manager API

Sie können iSCSI Volumes für FSX für ONTAP mithilfe der Cloud Manager API erstellen und diese in Ihrer Arbeitsumgebung managen.



=== Wählen Sie bei der Erstellung von Volumes Volumeneinheiten aus

Sie können link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-add-fsx-volumes.html#creating-volumes["Wählen Sie beim Erstellen von Volumes Volume-Einheiten (gib oder tib) aus"]FSX für ONTAP nutzen.



== Oktober 4 2021



=== Erstellen Sie CIFS Volumes mit Cloud Manager

Jetzt können Sie link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-add-fsx-volumes.html#creating-volumes["Erstellen Sie CIFS Volumes in FSX für ONTAP mit Cloud Manager"].



=== Bearbeiten von Volumes mit Cloud Manager

Jetzt können Sie link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-manage-fsx-volumes.html#editing-volumes["Bearbeiten Sie FSX für ONTAP Volumes mit Cloud Manager"].



== September 2021



=== Unterstützung von Amazon FSX für NetApp ONTAP

* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX für NetApp ONTAP"^] Ist ein vollständig gemanagter Service, mit dem Kunden Filesysteme auf Basis des NetApp ONTAP Storage-Betriebssystems starten und ausführen können. FSX für ONTAP bietet dieselben Funktionen, Performance und Managementfunktionen, die NetApp Kunden vor Ort nutzen. Außerdem bietet sie die Einfachheit, Agilität, Sicherheit und Skalierbarkeit eines nativen AWS Service.
+
link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/concept-fsx-aws.html["Weitere Informationen zu Amazon FSX für NetApp ONTAP"].

* Sie können eine FSX für ONTAP Arbeitsumgebung in Cloud Manager konfigurieren.
+
link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-creating-fsx-working-environment.html["Erstellen einer Arbeitsumgebung von Amazon FSX für NetApp ONTAP"].

* Mit einem Connector in AWS und Cloud Manager lassen sich Volumes erstellen und managen, Daten replizieren und FSX für ONTAP in NetApp Cloud-Services wie Data Sense und Cloud Sync integrieren.
+
link:https://docs.netapp.com/us-en/bluexp-classification/task-scanning-fsx.html["Erste Schritte mit Cloud Data Sense für Amazon FSX for NetApp ONTAP"^].


