---
sidebar: sidebar 
permalink: start/concept-fsx-aws.html 
keywords: Amazon FSx for NetApp ONTAP, volumes, aws, access key, secret key, cloud manager 
summary: Amazon FSX for NetApp ONTAP ist ein vollständig gemanagter Service, mit dem Kunden Dateisysteme mit dem NetApp ONTAP Storage-Betriebssystem starten und ausführen können. FSX für ONTAP bietet dieselben Funktionen, Performance und Managementfunktionen, die NetApp Kunden heute vor Ort nutzen. Außerdem bietet sie die Einfachheit, Agilität, Sicherheit und Skalierbarkeit eines nativen AWS Service. 
---
= Weitere Informationen zu Amazon FSX für NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX für NetApp ONTAP"^] Ist ein vollständig gemanagter Service, mit dem Kunden Filesysteme auf Basis des NetApp ONTAP Storage-Betriebssystems starten und ausführen können. FSX für ONTAP bietet dieselben Funktionen, Performance und Managementfunktionen, die NetApp Kunden vor Ort nutzen. Außerdem bietet sie die Einfachheit, Agilität, Sicherheit und Skalierbarkeit eines nativen AWS Service.



== Funktionen

* Die Konfiguration oder das Management von Storage-Systemen, Software oder Backups ist nicht erforderlich.
* Unterstützung für CIFS-, NFSv3-, NFSv4.x- und SMB v2.0 - v3.1.1-Protokolle
* Kostengünstige, praktisch unbegrenzte Storage-Kapazität auf dem verfügbaren IA Storage Tier (selten zugegriffen)
* Für die Ausführung auf latenzempfindlichen Applikationen, einschließlich Oracle RAC, zertifiziert.
* Optionen für Pakete und Pay-as-you-go-Preise:




== Zusätzliche Funktionen in BlueXP

* Amazon FSX for NetApp ONTAP wird unterstützt, wenn BlueXP im _Standard_- oder _Restricted_-Modus verwendet wird.
+
** Der Standardmodus nutzt die BlueXP SaaS-Ebene für volle Funktionalität.
** Der eingeschränkte Modus ist für Unternehmen mit Konnektivitätsbeschränkungen verfügbar.
+
Siehe link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-modes.html["BlueXP Implementierungsmodi"^] Finden Sie weitere Informationen.



* Wird Verwendet link:https://docs.netapp.com/us-en/cloud-manager-family/["BlueXP"^] (Cloud Manager) und einen Connector in AWS können Sie Volumes erstellen und managen, Daten replizieren und FSX for ONTAP mit NetApp Cloud-Services wie der BlueXP Klassifizierung und der BlueXP Kopier- und Synchronisierungsfunktion (Cloud Sync) integrieren.
* Mithilfe von künstlicher Intelligenz (KI) hilft Ihnen die BlueXP Klassifizierung (Cloud Data Sense) dabei, den Datenkontext zu verstehen und sensible Daten in Ihren FSX für ONTAP-Konten zu identifizieren. https://docs.netapp.com/us-en/cloud-manager-data-sense/concept-cloud-compliance.html["Weitere Informationen ."^].
* Mit der BlueXP Kopier- und Synchronisierungsfunktion können Sie die Datenmigration zu jedem beliebigen Ziel in der Cloud oder vor Ort automatisieren. https://docs.netapp.com/us-en/cloud-manager-sync/concept-cloud-sync.html["Weitere Informationen ."^]




== Kosten

Ihr FSX für ONTAP Konto wird von AWS verwaltet und nicht von BlueXP. Siehe https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX for NetApp ONTAP: Erste Schritte"^].

Durch die Nutzung des Connectors in AWS und der optionalen Datenservices wie BlueXP Kopier- und Synchronisierungsfunktionen und BlueXP Klassifizierung entstehen zusätzliche Kosten.



== Unterstützte Regionen

https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Unterstützte Amazon Regionen anzeigen."^]



== Hilfe wird abgerufen

Amazon FSX für NetApp ONTAP ist eine AWS-First-Party-Lösung. Wenn Sie Fragen oder technische Support-Probleme im Zusammenhang mit Ihrem ONTAP Filesystem, Ihrer Infrastruktur oder jeder Lösung, die diesen Service verwendet, haben Sie über das Support-Center in Ihrer AWS-Konsole einen Support-Fall für AWS zu eröffnen. Wählen Sie den Service „FSX for ONTAP“ und die entsprechende Kategorie aus. Geben Sie die verbleibenden Informationen an, die zur Erstellung Ihres AWS-Supportfalls erforderlich sind.

Bei allgemeinen Fragen zu BlueXP oder BlueXP Storage-Lösungen und -Services können Sie mit dem Inline-Chat von BlueXP beginnen.

Bei technischen Support-Problemen im Zusammenhang mit BlueXP oder BlueXP Storage-Lösungen und -Services können Sie über die Seriennummer des BlueXP Kundenkontos ein NetApp Support Ticket eröffnen. Das müssen Sie link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/support/task-support-registration.html["registrieren Sie Ihr BlueXP-Konto"^] Um den Support zu aktivieren.
